
import { ProductListing } from "@/redux/services/homeServices";
import { wrapper } from "@/redux/store";
import dynamic from "next/dynamic";
import Head from "next/head";

const HomeProduct = dynamic(() => import("@/components/HomeProduct"));

export default function Home({products}) {
  console.log('products',products)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <HomeProduct products={products}/>
      </main>
    </>
  );
}
export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (ctx) => {
    let products = [];

    try {
      const response = await store.dispatch(ProductListing()).unwrap();
      products = response;
    } catch (error) {
      console.error(error);
    }

    return {
      props: { products } || [],
    };
  }
);